### ISSUE TITLE
"Remember these settings?" incorrectly saves settings for both disc types

### ISSUE THREAD

**Issue by Kazuto88** [emukidid/cleanrip#67]
This was discovered on the current version, 2.1.1. I started by ripping my GCN games. I chose "No" for using a Datel disc, then "Yes" to remember these settings. After finishing with GCN, I switched to a Wii disc, a dual-layer disc no less, and was never prompted to pick Wii-specific settings, such as dual-layer, chunk size, or new device per-chunk.

Presumably, the rip proceeded with default settings, as I wound up with 5 chunks, and it kept prompting me to connect the next device.

EDIT: After posting, I realized the dual-layer option is really something that shouldn't be persistent for the session. Why? Because when you lock-in a setting for that, it forces you to close out in order to rip a disc of the other type, rather than being able to use the same device settings and just pick, per-game, whether it's a dual-layer disc. I know the number of dual-layer game discs is slim, but still.

**Comment by calc84maniac** [comment]
While the default auto dual-layer detection has been added, I've just run into the same core issue described here, which is that I was ripping GCN discs with remembered settings but never got prompted for any Wii settings after inserting my first Wii disc. The default chunking options weren't ideal because I'm dumping to exFAT.
